# do a . /home/ai/bin/ai_profile first!!!
FILES= \
	com/duckdigit/util/*/*.java  \
	com/duckdigit/pick/*.java  \
	com/duckdigit/ai/adapters/sagitta/*.java 

all:
	@-mkdir $(AICLASSES)
	javac -d $(AICLASSES) -classpath $(AICLASSES)  $(FILES)
	

clean:
